services:
  postgres:
    container_name: utlc_db_container
    image: 'postgres:16'
    volumes:
      - './csv'
    environment:
      - 'POSTGRES_DB=utlc_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'