spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/utlc_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
#      hbm2ddl.auto: create
      batch_size: 50
      fetch_size: 50
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false