--liquibase formatted sql

--changeset ayushchenko:1
INSERT INTO client_status (name, created_by)
VALUES ('active', 'YAE'),
       ('passive', 'YAE');

--changeset ayushchenko:2
INSERT INTO client_status_localization (client_status_id, language_code, localized_name)
VALUES (1, 'en', 'active'),
       (1, 'ru', 'активный'),
       (2, 'en', 'passive'),
       (2, 'ru', 'пассивный');

--changeset ayushchenko:3
INSERT INTO shipment_status (name, created_by)
VALUES ('Checking order data', 'YAE'),
       ('Attention(!)', 'YAE'),
       ('Clarifying order details with the sender', 'YAE'),
       ('Sent vehicle to the sender''s warehouse', 'YAE'),
       ('Picked up and en route to the consolidation warehouse', 'YAE'),
       ('consolidation warehouse (Europe)', 'YAE'),
       ('consolidation warehouse (China)', 'YAE'),
       ('consolidation warehouse (USA)', 'YAE'),
       ('In transit (sea)', 'YAE'),
       ('In transit (air)', 'YAE'),
       ('In transit (Europe)', 'YAE'),
       ('Crossing the border', 'YAE'),
       ('Customs clearance', 'YAE'),
       ('Arriving at the pickup warehouse', 'YAE'),
       ('Ready for pickup', 'YAE'),
       ('In storage', 'YAE'),
       ('Delivered', 'YAE'),
       ('Cancelled', 'YAE');

--changeset ayushchenko:4
INSERT INTO shipment_status_localization (shipment_status_id, language_code, localized_name)
VALUES (1, 'en', 'Checking order data'),
       (1, 'ru', 'Проверяем данные заявки'),
       (2, 'en', 'Attention(!)'),
       (2, 'ru', 'Внимание(!)'),
       (3, 'en', 'Clarifying order details with the sender'),
       (3, 'ru', 'Уточняем детали заказа с отправителем'),
       (4, 'en', 'Sent vehicle to the sender''s warehouse'),
       (4, 'ru', 'Отправили машину на склад отправителя'),
       (5, 'en', 'Picked up and en route to the consolidation warehouse'),
       (5, 'ru', 'Забран и едет на склад консолидации'),
       (6, 'en', 'Consolidation warehouse (Europe)'),
       (6, 'ru', 'Склад консолидации (Европа)'),
       (7, 'en', 'Consolidation warehouse (China)'),
       (7, 'ru', 'Склад консолидации (Китай)'),
       (8, 'en', 'Consolidation warehouse (USA)'),
       (8, 'ru', 'Склад консолидации (США)'),
       (9, 'en', 'In transit (sea)'),
       (9, 'ru', 'В пути (море)'),
       (10, 'en', 'In transit (air)'),
       (10, 'ru', 'В пути (Самолет)'),
       (11, 'en', 'In transit (Europe)'),
       (11, 'ru', 'В пути (Европа)'),
       (12, 'en', 'Crossing the border'),
       (12, 'ru', 'Проходит границу'),
       (13, 'en', 'Customs clearance'),
       (13, 'ru', 'Таможенное оформление'),
       (14, 'en', 'Arriving at the pickup warehouse'),
       (14, 'ru', 'Прибывает на склад выдачи'),
       (15, 'en', 'Ready for pickup'),
       (15, 'ru', 'Готов к выдаче'),
       (16, 'en', 'In storage'),
       (16, 'ru', 'На хранении'),
       (17, 'en', 'Delivered'),
       (17, 'ru', 'Доставлен'),
       (18, 'en', 'Cancelled'),
       (18, 'ru', 'Отменен');

--changeset ayushchenko:5
INSERT INTO administrator (username, email, firstname, lastname, role, created_by)
VALUES ('COM', 'com@u-tlc.ru', 'Алексей', 'Ющенко', 'ADMIN', 'YAE'),
       ('USER', '13yae13@gmail.com', 'Василий', 'Николаевич', 'USER', 'YAE');

--changeset ayushchenko:6
INSERT INTO country (name, code)
VALUES ('AUSTRALIA', 'AU'),
       ('AUSTRIA', 'AT'),
       ('BELGIUM', 'BE'),
       ('BELARUS', 'BY'),
       ('BOSNIA & HERZEGOVINA', 'BA'),
       ('BRASIL', 'BR'),
       ('BRITISH VIRGIN ISLANDS', 'BV'),
       ('BULGARIA', 'BG'),
       ('BANGLADESH', 'BD'),
       ('CANADA', 'CA'),
       ('CHINA', 'CN'),
       ('CROATIA', 'HR'),
       ('CYPRUS', 'CY'),
       ('CZECH REPUBLIC', 'CZ'),
       ('DENMARK', 'DM'),
       ('ENGLAND', 'UK'),
       ('ESTONIA', 'EE'),
       ('FINLAND', 'FI'),
       ('FRANCE', 'FR'),
       ('GERMANY', 'DE'),
       ('GREECE', 'GR'),
       ('HUNGARY', 'HU'),
       ('INDIA', 'IN'),
       ('INDONESIA', 'ID'),
       ('IRELAND', 'IR'),
       ('ISRAIL', 'IL'),
       ('ITALY', 'IT'),
       ('JAPAN', 'JP'),
       ('KAZAHSTAN', 'KZ'),
       ('LATVIA', 'LV'),
       ('LIECHTENSTEIN', 'LI'),
       ('LITHUANIA', 'LT'),
       ('MALAYSIA', 'MY'),
       ('MONTENEGRO', 'MO'),
       ('NEPAL', 'NP'),
       ('NETHERLANDS', 'NL'),
       ('NEW ZEALAND', 'NZ'),
       ('PAKISTAN', 'PK'),
       ('PHILIPPINES', 'PH'),
       ('POLAND', 'PL'),
       ('PORTUGAL', 'PT'),
       ('RUSSIA', 'RU'),
       ('SLOVAKIA', 'SK'),
       ('SLOVENIA', 'SL'),
       ('SPAIN', 'ES'),
       ('SWEDEN', 'SE'),
       ('SWITZERLAND', 'CH'),
       ('TAIWAN', 'TW'),
       ('THAILAND', 'TH'),
       ('TURKEY', 'TR'),
       ('UNITED ARABIAN EMIRATES', 'AE'),
       ('UNITED STATES OF AMERICA', 'US'),
       ('UZBEKISTAN', 'UZ'),
       ('VIETNAM', 'VN');

--changeset ayushchenko:7
INSERT INTO country_localization (country_id, language_code, localized_name)
VALUES (1, 'en', 'AUSTRALIA'),
       (1, 'ru', 'АВСТРАЛИЯ'),
       (2, 'en', 'AUSTRIA'),
       (2, 'ru', 'АВСТРИЯ'),
       (3, 'en', 'BELGIUM'),
       (3, 'ru', 'БЕЛЬГИЯ'),
       (4, 'en', 'BELARUS'),
       (4, 'ru', 'БЕЛАРУСЬ'),
       (5, 'en', 'BOSNIA & HERZEGOVINA'),
       (5, 'ru', 'БОСНИЯ И ГЕРЦЕГОВИНА'),
       (6, 'en', 'BRAZIL'),
       (6, 'ru', 'БРАЗИЛИЯ'),
       (7, 'en', 'BRITISH VIRGIN ISLANDS'),
       (7, 'ru', 'БРИТАНСКИЕ ВИРГИНСКИЕ ОСТРОВА'),
       (8, 'en', 'BULGARIA'),
       (8, 'ru', 'БОЛГАРИЯ'),
       (9, 'en', 'BANGLADESH'),
       (9, 'ru', 'БАНГЛАДЕШ'),
       (10, 'en', 'CANADA'),
       (10, 'ru', 'КАНАДА'),
       (11, 'en', 'CHINA'),
       (11, 'ru', 'КИТАЙ'),
       (12, 'en', 'CROATIA'),
       (12, 'ru', 'ХОРВАТИЯ'),
       (13, 'en', 'CYPRUS'),
       (13, 'ru', 'КИПР'),
       (14, 'en', 'CZECH REPUBLIC'),
       (14, 'ru', 'ЧЕШСКАЯ РЕСПУБЛИКА'),
       (15, 'en', 'DENMARK'),
       (15, 'ru', 'ДАНИЯ'),
       (16, 'en', 'ENGLAND'),
       (16, 'ru', 'АНГЛИЯ'),
       (17, 'en', 'ESTONIA'),
       (17, 'ru', 'ЭСТОНИЯ'),
       (18, 'en', 'FINLAND'),
       (18, 'ru', 'ФИНЛЯНДИЯ'),
       (19, 'en', 'FRANCE'),
       (19, 'ru', 'ФРАНЦИЯ'),
       (20, 'en', 'GERMANY'),
       (20, 'ru', 'ГЕРМАНИЯ'),
       (21, 'en', 'GREECE'),
       (21, 'ru', 'ГРЕЦИЯ'),
       (22, 'en', 'HUNGARY'),
       (22, 'ru', 'ВЕНГРИЯ'),
       (23, 'en', 'INDIA'),
       (23, 'ru', 'ИНДИЯ'),
       (24, 'en', 'INDONESIA'),
       (24, 'ru', 'ИНДОНЕЗИЯ'),
       (25, 'en', 'IRELAND'),
       (25, 'ru', 'ИРЛАНДИЯ'),
       (26, 'en', 'ISRAEL'),
       (26, 'ru', 'ИЗРАИЛЬ'),
       (27, 'en', 'ITALY'),
       (27, 'ru', 'ИТАЛИЯ'),
       (28, 'en', 'JAPAN'),
       (28, 'ru', 'ЯПОНИЯ'),
       (29, 'en', 'KAZAHSTAN'),
       (29, 'ru', 'КАЗАХСТАН'),
       (30, 'en', 'LATVIA'),
       (30, 'ru', 'ЛАТВИЯ'),
       (31, 'en', 'LIECHTENSTEIN'),
       (31, 'ru', 'ЛИХТЕНШТЕЙН'),
       (32, 'en', 'LITHUANIA'),
       (32, 'ru', 'ЛИТВА'),
       (33, 'en', 'MALAYSIA'),
       (33, 'ru', 'МАЛАЙЗИЯ'),
       (34, 'en', 'MONTENEGRO'),
       (34, 'ru', 'ЧЕРНОГОРИЯ'),
       (35, 'en', 'NEPAL'),
       (35, 'ru', 'НЕПАЛ'),
       (36, 'en', 'NETHERLANDS'),
       (36, 'ru', 'НИДЕРЛАНДЫ'),
       (37, 'en', 'NEW ZEALAND'),
       (37, 'ru', 'НОВАЯ ЗЕЛАНДИЯ'),
       (38, 'en', 'PAKISTAN'),
       (38, 'ru', 'ПАКИСТАН'),
       (39, 'en', 'PHILIPPINES'),
       (39, 'ru', 'ФИЛИППИНЫ'),
       (40, 'en', 'POLAND'),
       (40, 'ru', 'ПОЛЬША'),
       (41, 'en', 'PORTUGAL'),
       (41, 'ru', 'ПОРТУГАЛИЯ'),
       (42, 'en', 'RUSSIA'),
       (42, 'ru', 'РОССИЯ'),
       (43, 'en', 'SLOVAKIA'),
       (43, 'ru', 'СЛОВАКИЯ'),
       (44, 'en', 'SLOVENIA'),
       (44, 'ru', 'CЛОВЕНИЯ'),
       (45, 'en', 'SPAIN'),
       (45, 'ru', 'ИСПАНИЯ'),
       (46, 'en', 'SWEDEN'),
       (46, 'ru', 'ШВЕЦИЯ'),
       (47, 'en', 'SWITZERLAND'),
       (47, 'ru', 'ШВЕЙЦАРИЯ'),
       (48, 'en', 'TAIWAN'),
       (48, 'ru', 'ТАЙВАНЬ'),
       (49, 'en', 'THAILAND'),
       (49, 'ru', 'ТАИЛАНД'),
       (50, 'en', 'TURKEY'),
       (50, 'ru', 'ТУРЦИЯ'),
       (51, 'en', 'UNITED ARABIAN EMIRATES'),
       (51, 'ru', 'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ'),
       (52, 'en', 'UNITED STATES OF AMERICA'),
       (52, 'ru', 'СОЕДИНЕННЫЕ ШТАТЫ АМЕРИКИ'),
       (53, 'en', 'UZBEKISTAN'),
       (53, 'ru', 'УЗБЕКИСТАН'),
       (54, 'en', 'VIETNAM'),
       (54, 'ru', 'ВЬЕТНАМ');

--changeset ayushchenko:8
INSERT INTO manufacturer (name, country_id, created_by)
VALUES ('ALTAMODA', 27, 'YAE'),
       ('ANGELO CAPPELLINI', 27, 'YAE');

--changeset ayushchenko:9
INSERT INTO warehouse (name, country_id, created_by)
VALUES ('P & B Terminal', 30, 'YAE'),
       ('ABX Terminal', 30, 'YAE'),
       ('ANDREETTO & ZANON', 27, 'YAE'),
       ('AN TRANSPORTS', 30, 'YAE'),
       ('ARROW', 30, 'YAE'),
       ('EXCELLENCE', 45, 'YAE'),
       ('IHS', 20, 'YAE'),
       ('KONEKTA CARGO', 32, 'YAE'),
       ('LASL', 52, 'YAE'),
       ('MINISPED', 45, 'YAE'),
       ('MPG INTERNATIONAL', 20, 'YAE'),
       ('N LOGISTIKS', 30, 'YAE'),
       ('NTZ', 20, 'YAE'),
       ('RESKO', 32, 'YAE'),
       ('ROSTERMINALS', 30, 'YAE'),
       ('STO EXPRESS', 42, 'YAE'),
       ('SVO GROUP UAB', 30, 'YAE'),
       ('TRUST LINE', 42, 'YAE'),
       ('Ю-ТЛК МОСКВА', 42, 'YAE'),
       ('VINGES', 32, 'YAE'),
       ('VLADIVOSTOK 1', 42, 'YAE');

--changeset ayushchenko:10
INSERT INTO pick_up_point (name, country_id, address)
VALUES ('Ю-ТЛК Москва', 42, 'Россия, г. Королёв, Ярославский проезд, 3а'),
       ('Ю-ТЛК Санкт-Петербург', 42, 'Россия, Санкт-Петербург, ул. Московская, 13');

--changeset ayushchenko:11
INSERT INTO business_type (name, description, created_by)
VALUES ('Микропредприятие', 'до 15 человек или оборот до 120 млн рублей', 'YAE'),
       ('Малый бизнес', '16-100 человек или оборот до 800 млн рублей', 'YAE'),
       ('Средний бизнес', '101-250 человек или оборот до 2 млрд рублей', 'YAE'),
       ('Крупный бизнес', '251< человек или оборот от 2 млрд рублей', 'YAE'),
       ('Физлицо', 'Частное лицо, совершающее покупки для личных, некоммерческих целей', 'YAE');

--changeset ayushchenko:12
INSERT INTO industry_type (name, created_by)
VALUES ('Производство', 'YAE'),
       ('Розничная торговля', 'YAE'),
       ('Фармацевтика', 'YAE'),
       ('Автомобильная промышленность', 'YAE'),
       ('Технологии и электроника', 'YAE'),
       ('Строительство', 'YAE'),
       ('Пищевая Промышленность', 'YAE'),
       ('eCommerce', 'YAE'),
       ('Агропромышленный Сектор', 'YAE');

--changeset ayushchenko:13
INSERT INTO priority (name, created_by)
VALUES ('Стандартный', 'YAE'),
       ('Высокий', 'YAE');

--changeset ayushchenko:14
INSERT INTO agent (name, phone, commentary)
VALUES ('Test name 1', '+7 383 912 38 58', 'This is a test commentary'),
       ('Test name 2', '+39 5383 912 38 58', 'This is a test commentary');

--changeset ayushchenko:15
INSERT INTO invoice_status (name)
VALUES ('Paid'),
       ('Unpaid'),
       ('Overdue');